query getPopularCategories {
  featuredBoard {
    code
    success
    message
    data {
      categories {
        id
        nameEn
        nameAr
        isActive
        code
        isFeatured
        image {
          file
        }
      }
      services {
        id
        nameEn
        nameAr
        code
        isFeatured
        isActive
        categoryId
        slug
        image {
          file
        }
      }
    }
  }
}
